### ISSUE TITLE
ARM server error

### ISSUE THREAD

**Issue by GeekWorkCode** [Ukenn2112/ChatGPTelegramBot#2]
Traceback (most recent call last):
  File "bot.py", line 10, in <module>
    from revChatGPT.revChatGPT import AsyncChatbot
  File "/usr/local/lib/python3.8/dist-packages/revChatGPT/revChatGPT.py", line 12, in <module>
    from OpenAIAuth.OpenAIAuth import OpenAIAuth, Debugger
  File "/usr/local/lib/python3.8/dist-packages/OpenAIAuth/OpenAIAuth.py", line 6, in <module>
    import tls_client
  File "/usr/local/lib/python3.8/dist-packages/tls_client/__init__.py", line 15, in <module>
    from .sessions import Session
  File "/usr/local/lib/python3.8/dist-packages/tls_client/sessions.py", line 1, in <module>
    from .cffi import request
  File "/usr/local/lib/python3.8/dist-packages/tls_client/cffi.py", line 15, in <module>
    library = ctypes.cdll.LoadLibrary(f'{root_dir}/dependencies/tls-client{file_ext}')
  File "/usr/lib/python3.8/ctypes/__init__.py", line 451, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/local/lib/python3.8/dist-packages/tls_client/dependencies/tls-client-amd64.so: cannot open shared object file: No such file or directory

**Comment by Ukenn2112** [comment]
这个情况看起来是上游的问题，你能运行起来discode_chatgpt的docker么

**Comment by GeekWorkCode** [comment]
> 这个情况看起来是上游的问题，你能运行起来discode_chatgpt的docker么

可以 我就是跑起来discode_chatgpt  没问题，才推荐参考那个的，因为主要玩tg，我看他用revChatGPT==0.0.44， 我准备改成这个试下

**Comment by Ukenn2112** [comment]
0.0.44 版本异步有点问题，会导致跑不起来。我可能需要修改一下才能支持0.0.44版本

**Comment by GeekWorkCode** [comment]
> 0.0.44 版本异步有点问题，会导致跑不起来。我可能需要修改一下才能支持0.0.44版本
嗯 我改成0.0.44 运行报这个错
Traceback (most recent call last):
  File "bot.py", line 199, in <module>
    asyncio.get_event_loop().run_until_complete(get_cf_clearance())
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "bot.py", line 191, in get_cf_clearance
    raise Exception('获取 cf_clearance 失败')
Exception: 获取 cf_clearance 失败

**Comment by Ukenn2112** [comment]
7ee44cbbc4b94dbcb0258febf6b98d5143370897 已支持并修复
