### ISSUE TITLE
It gives out an error.

### ISSUE THREAD

**Issue by MrCatBoss** [Ukenn2112/ChatGPTelegramBot#3]
Sorry, I don't know much about code, so I want to ask what does it mean?

`Debugger enabled on OpenAIAuth
Traceback (most recent call last):
  File "/mnt/chatgpt/telegram/bot.py", line 22, in <module>
    chatbot = AsyncChatbot(config.get('session_token'), debug=True)
  File "/mnt/chatgpt/telegram/revChatGPT.py", line 74, in __init__
    self.get_uuid()
  File "/mnt/chatgpt/telegram/revChatGPT.py", line 187, in get_uuid
    self.uuid = response.json()["id"]
KeyError: 'id'
`

**Comment by Ukenn2112** [comment]
Request to get the id did not get, this project is currently no longer maintained, you can try other projects
